### ISSUE TITLE
Is there  a way to detect current window is editable? e.g. in a form/dialog ?

### ISSUE THREAD

**Issue by zw963** [kui/rbindkeys#6]
I just rebind difference keybinding when in/out editable status.

e.g.  Firefox view page is a keybinding, in a form reply message is another keybinding.

Thanks.

**Comment by kui** [comment]
It's difficult, because rbindkeys can get only app name or window title from X Window System.

If you want to rebind by rbindkeys at any cost, create an user script that change the page title when an editable DOM element was focused and add a rule that detects the changed window(page) title. But... I think it's too complex and the way cannot be used in the pages that edits it's titles

**Comment by zw963** [comment]
Thanks very much.

What I do is just your want me to do, e.g. I write a wrapper script for nano.
make it can change current Terminal title, this will make me work on remote
ssh host so comfortable.

``` nano
#!/bin/sh

SCRIPT_DIRECTORY=${0%/*}

set_term_title(){
    echo -en "\033]0;$1\a"
}

if [ -z "$SSH_CLIENT$SSH_TTY" ]; then
    old_title=$(xprop -id $(xprop -root _NET_ACTIVE_WINDOW | cut -d ' ' -f 5) WM_NAME |cut -d'"' -f2)
fi

set_term_title "nano $@"
$SCRIPT_DIRECTORY/nano_binary "$@"

if [ "$SSH_CLIENT$SSH_TTY" ]; then
    set_term_title "$USER@$HOSTNAME"
else
    set_term_title "$old_title"
fi
```

in fact, detect editable status is not so needful now, still thanks for reply.
